site_name: Dans Docs
pages:
  - Home: index.md
  - Languages:
    - Python: languages/python.md
    - JavaScript: languages/javascript.md
    - Java: languages/java.md
    - Scala: languages/scala.md
    - Go: languages/go.md
  - Containerisation:
    - Docker: containerisation/docker.md
    - Kubernetes: containerisation/kubernetes.md
theme: slate
