site_name: Dans Docs
pages:
  - Home: index.md
  - Languages:
    - Python: python.md
    - JavaScript: javascript.md
    - Java: java.md
    - Scala: scala.md
    - Go: go.md
  - Containerisation:
    - Docker: docker.md
    - Kubernetes: kubernetes.md
theme: readthedocs
