site_name: Dans Docs
nav:
  - Home: index.md
  - Publications: publications/dev.md

  - Languages:
    - Python: languages/python.md
    - JavaScript: languages/javascript.md
    - Java: languages/java.md
    - Scala: languages/scala.md
    - Go: languages/go.md

  - Containerisation:
    - Docker: containerisation/docker.md
    - Kubernetes: containerisation/kubernetes.md

  - AWS:
    - AWS: aws/aws.md
    - CLI: aws/cli.md
    - IAM: aws/iam.md
    - EC2: aws/ec2.md
    - RDS: aws/rds.md
    - ELB: aws/elb.md
    - Route 53: aws/r53.md
    - Elasticache: aws/elasticache.md
    - Dynamo DB: aws/dynamo.md
    - Dax: aws/dax.md
    - KMS: aws/kms.md
    - CloudWatch: aws/cloudwatch.md
    - S3: aws/s3.md
    - CloudFront: aws/cloudfront.md
    - Serverless: aws/serverless.md
    - Lambda: aws/lambda.md
    - API Gateway: aws/api-gateway.md
    - Step Functions: aws/step-functions.md
    - X Ray: aws/x-ray.md
    - SQS: aws/sqs.md
    - SNS: aws/sns.md
    - SES: aws/ses.md
    - Elastic Beanstalk: aws/elasticbeanstalk.md
    - Kinesis: aws/kinesis.md
    - CI/CD: aws/ci-cd.md
    - CodeCommit: aws/codecommit.md
    - CodeDeploy: aws/codedeploy.md
    - CodeBuild: aws/codebuild.md
    - CloudFormation: aws/cloudformation.md
    - SAM: aws/sam.md

theme:
  name: material
  favicon: https://lh3.googleusercontent.com/m2Zy-ujFWYyQUhg3uIuG_YDx00HB1v08cQ4CBJnd-v6LMPBpps3C4kvQriV0nObfI-I
  logo: https://lh3.googleusercontent.com/m2Zy-ujFWYyQUhg3uIuG_YDx00HB1v08cQ4CBJnd-v6LMPBpps3C4kvQriV0nObfI-I

  feature:
    tabs: true

  palette:
    primary: teal
    accent: cyan

repo_url: https://github.com/daniel40392/docs
repo_name: Dan's Docs
edit_uri: edit/master/docs

markdown_extensions:
  - admonition
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.mark
  - smarty
